CREATE TABLE verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    passcode VARCHAR(6) NOT NULL,
    tries INTEGER NOT NULL DEFAULT 0,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    CONSTRAINT chk_verifications_tries CHECK (tries >= 0)
);

CREATE INDEX idx_verifications_email ON verifications(email);
